name: Azure ARM

on:
  push:
    branches:
      - production
      - main
  workflow_dispatch:

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/production' && 'prod' || 'dev' }}
  REGION: australiaeast

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build infrastructure with Bicep
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: "subscription"
          template: .bicep/main.bicep
          parameters: "environment=${{ env.ENVIRONMENT }} location=${{ env.REGION }}"
          failOnStdErr: false
          region: australiaeast

      - name: Log out of Azure
        run: az logout
